import { createFileRoute, Link } from "@tanstack/react-router";
import { useState } from "react";
import { Download, FileText, Lock, Search, Sparkles, Upload } from "lucide-react";
import { PageHeader } from "@/components/portal/PageHeader";
import { StatusBadge } from "@/components/portal/StatusBadge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { useClientPortal, downloadDocumentRequest, downloadGeneratedDocumentRequest } from "@/lib/client-portal-api";
import { ClientPortalError, ClientPortalLoading } from "@/lib/client-portal-page";
import { toast } from "sonner";

export const Route = createFileRoute("/_portal/documents")({
  head: () => ({
    meta: [
      { title: "Documents — FG Debt Advisor AI" },
      { name: "description", content: "Your encrypted document vault: uploaded evidence and documents generated by FG Debt Advisor AI for your case." },
      { property: "og:title", content: "Documents — FG Debt Advisor AI" },
      { property: "og:description", content: "Securely stored evidence and generated case documents." },
    ],
  }),
  component: DocumentsPage,
});

function DocumentsPage() {
  const { data, isLoading, isError } = useClientPortal();
  if (isLoading) return <ClientPortalLoading />;
  if (isError || !data) return <ClientPortalError />;
  return <DocumentsContent portal={data.portal} />;
}

function DocumentsContent({ portal }: { portal: import("@/lib/client-portal-api").ClientPortalData }) {
  const [query, setQuery] = useState("");
  const uploaded = portal.documents.filter((d) =>
    (d.name + d.type).toLowerCase().includes(query.toLowerCase()),
  );
  const generated = portal.generatedDocuments.filter((d) =>
    (d.name + d.type).toLowerCase().includes(query.toLowerCase()),
  );

  return (
    <>
      <PageHeader
        eyebrow="Records"
        title="Documents"
        description="Everything you've sent us and everything we've produced for your case, encrypted at rest."
        actions={
          <Button asChild>
            <Link to="/upload-documents">
              <Upload className="size-4" /> Upload document
            </Link>
          </Button>
        }
      />

      <div className="mb-6 flex flex-wrap items-center gap-4">
        <div className="relative min-w-64 flex-1">
          <Search className="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" />
          <Input
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            placeholder="Search documents"
            className="pl-9"
            aria-label="Search documents"
          />
        </div>
        <p className="inline-flex items-center gap-2 rounded-full border border-border bg-secondary/50 px-3 py-1.5 text-xs text-muted-foreground">
          <Lock className="size-3.5 text-success" /> AES-256 encrypted · UK data residency
        </p>
      </div>

      <section className="surface-card overflow-hidden">
        <Tabs defaultValue="uploaded">
          <div className="flex flex-wrap items-center justify-between gap-4 p-6 pb-4">
            <h2 className="text-lg font-semibold">Document vault</h2>
            <TabsList>
              <TabsTrigger value="uploaded">Uploaded ({uploaded.length})</TabsTrigger>
              <TabsTrigger value="generated">Generated ({generated.length})</TabsTrigger>
            </TabsList>
          </div>

          <TabsContent value="uploaded">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Document</TableHead>
                  <TableHead className="hidden sm:table-cell">Type</TableHead>
                  <TableHead className="hidden md:table-cell">Uploaded</TableHead>
                  <TableHead>Status</TableHead>
                  <TableHead className="text-right">Action</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {uploaded.map((d) => (
                  <TableRow key={d.id} className="transition-colors hover:bg-muted/60">
                    <TableCell>
                      <div className="flex items-center gap-3">
                        <span className="grid size-9 shrink-0 place-items-center rounded-lg bg-secondary/70 text-primary">
                          <FileText className="size-4" />
                        </span>
                        <div>
                          <p className="text-sm font-medium">{d.name}</p>
                          <p className="text-xs text-muted-foreground">{d.size}</p>
                        </div>
                      </div>
                    </TableCell>
                    <TableCell className="hidden text-sm text-muted-foreground sm:table-cell">{d.type}</TableCell>
                    <TableCell className="hidden text-sm text-muted-foreground md:table-cell">{d.date}</TableCell>
                    <TableCell>
                      <StatusBadge status={d.status} />
                    </TableCell>
                    <TableCell className="text-right">
                      <Button
                        variant="ghost"
                        size="sm"
                        aria-label={`Download ${d.name}`}
                        onClick={() => {
                          void downloadDocumentRequest(d.id, d.name).catch((error) => {
                            toast.error("Download failed", {
                              description: error instanceof Error ? error.message : "Please try again.",
                            });
                          });
                        }}
                      >
                        <Download className="size-4" />
                      </Button>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
            {uploaded.length === 0 && (
              <p className="p-10 text-center text-sm text-muted-foreground">No documents found.</p>
            )}
          </TabsContent>

          <TabsContent value="generated">
            <ul className="grid gap-4 p-6 pt-2 md:grid-cols-2 xl:grid-cols-3">
              {generated.map((d) => (
                <li key={d.id} className="rounded-xl border border-border p-5 transition-colors hover:border-accent">
                  <span className="grid size-10 place-items-center rounded-xl bg-accent/15 text-primary">
                    <Sparkles className="size-4" />
                  </span>
                  <p className="mt-4 text-sm font-semibold leading-snug">{d.name}</p>
                  <p className="mt-1 text-xs text-muted-foreground">
                    {d.type} · {d.date}
                  </p>
                  <Button
                    variant="outline"
                    size="sm"
                    className="mt-4 w-full"
                    disabled={d.status !== "Ready"}
                    onClick={() => {
                      void downloadGeneratedDocumentRequest(d.id, d.name).catch((error) => {
                        toast.error("Download failed", {
                          description: error instanceof Error ? error.message : "Please try again.",
                        });
                      });
                    }}
                  >
                    <Download className="size-4" /> Download
                  </Button>
                </li>
              ))}
            </ul>
            {generated.length === 0 && (
              <p className="p-10 text-center text-sm text-muted-foreground">No generated documents found.</p>
            )}
          </TabsContent>
        </Tabs>
      </section>
    </>
  );
}
