/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalRouteImport } from './routes/_portal'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PortalAssessmentRouteImport } from './routes/_portal.assessment'
import { Route as PortalAssistantRouteImport } from './routes/_portal.assistant'
import { Route as PortalCasesRouteImport } from './routes/_portal.cases'
import { Route as PortalDashboardRouteImport } from './routes/_portal.dashboard'
import { Route as PortalDebtSummaryRouteImport } from './routes/_portal.debt-summary'
import { Route as PortalDocumentsRouteImport } from './routes/_portal.documents'
import { Route as PortalFinancialSummaryRouteImport } from './routes/_portal.financial-summary'
import { Route as PortalMessagesRouteImport } from './routes/_portal.messages'
import { Route as PortalProfileRouteImport } from './routes/_portal.profile'
import { Route as PortalRecommendationRouteImport } from './routes/_portal.recommendation'
import { Route as PortalReferralsRouteImport } from './routes/_portal.referrals'
import { Route as PortalUploadDocumentsRouteImport } from './routes/_portal.upload-documents'
import { Route as PortalVerificationRouteImport } from './routes/_portal.verification'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/_portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalAssessmentRoute = PortalAssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAssistantRoute = PortalAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => PortalRoute,
} as any)
const PortalCasesRoute = PortalCasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDashboardRoute = PortalDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDebtSummaryRoute = PortalDebtSummaryRouteImport.update({
  id: '/debt-summary',
  path: '/debt-summary',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDocumentsRoute = PortalDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => PortalRoute,
} as any)
const PortalFinancialSummaryRoute = PortalFinancialSummaryRouteImport.update({
  id: '/financial-summary',
  path: '/financial-summary',
  getParentRoute: () => PortalRoute,
} as any)
const PortalMessagesRoute = PortalMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => PortalRoute,
} as any)
const PortalProfileRoute = PortalProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PortalRoute,
} as any)
const PortalRecommendationRoute = PortalRecommendationRouteImport.update({
  id: '/recommendation',
  path: '/recommendation',
  getParentRoute: () => PortalRoute,
} as any)
const PortalReferralsRoute = PortalReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => PortalRoute,
} as any)
const PortalUploadDocumentsRoute = PortalUploadDocumentsRouteImport.update({
  id: '/upload-documents',
  path: '/upload-documents',
  getParentRoute: () => PortalRoute,
} as any)
const PortalVerificationRoute = PortalVerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => PortalRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/assessment': typeof PortalAssessmentRoute
  '/assistant': typeof PortalAssistantRoute
  '/cases': typeof PortalCasesRoute
  '/dashboard': typeof PortalDashboardRoute
  '/debt-summary': typeof PortalDebtSummaryRoute
  '/documents': typeof PortalDocumentsRoute
  '/financial-summary': typeof PortalFinancialSummaryRoute
  '/messages': typeof PortalMessagesRoute
  '/profile': typeof PortalProfileRoute
  '/recommendation': typeof PortalRecommendationRoute
  '/referrals': typeof PortalReferralsRoute
  '/upload-documents': typeof PortalUploadDocumentsRoute
  '/verification': typeof PortalVerificationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/assessment': typeof PortalAssessmentRoute
  '/assistant': typeof PortalAssistantRoute
  '/cases': typeof PortalCasesRoute
  '/dashboard': typeof PortalDashboardRoute
  '/debt-summary': typeof PortalDebtSummaryRoute
  '/documents': typeof PortalDocumentsRoute
  '/financial-summary': typeof PortalFinancialSummaryRoute
  '/messages': typeof PortalMessagesRoute
  '/profile': typeof PortalProfileRoute
  '/recommendation': typeof PortalRecommendationRoute
  '/referrals': typeof PortalReferralsRoute
  '/upload-documents': typeof PortalUploadDocumentsRoute
  '/verification': typeof PortalVerificationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_portal': typeof PortalRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_portal/assessment': typeof PortalAssessmentRoute
  '/_portal/assistant': typeof PortalAssistantRoute
  '/_portal/cases': typeof PortalCasesRoute
  '/_portal/dashboard': typeof PortalDashboardRoute
  '/_portal/debt-summary': typeof PortalDebtSummaryRoute
  '/_portal/documents': typeof PortalDocumentsRoute
  '/_portal/financial-summary': typeof PortalFinancialSummaryRoute
  '/_portal/messages': typeof PortalMessagesRoute
  '/_portal/profile': typeof PortalProfileRoute
  '/_portal/recommendation': typeof PortalRecommendationRoute
  '/_portal/referrals': typeof PortalReferralsRoute
  '/_portal/upload-documents': typeof PortalUploadDocumentsRoute
  '/_portal/verification': typeof PortalVerificationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/assessment'
    | '/assistant'
    | '/cases'
    | '/dashboard'
    | '/debt-summary'
    | '/documents'
    | '/financial-summary'
    | '/messages'
    | '/profile'
    | '/recommendation'
    | '/referrals'
    | '/upload-documents'
    | '/verification'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/assessment'
    | '/assistant'
    | '/cases'
    | '/dashboard'
    | '/debt-summary'
    | '/documents'
    | '/financial-summary'
    | '/messages'
    | '/profile'
    | '/recommendation'
    | '/referrals'
    | '/upload-documents'
    | '/verification'
  id:
    | '__root__'
    | '/'
    | '/_portal'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/_portal/assessment'
    | '/_portal/assistant'
    | '/_portal/cases'
    | '/_portal/dashboard'
    | '/_portal/debt-summary'
    | '/_portal/documents'
    | '/_portal/financial-summary'
    | '/_portal/messages'
    | '/_portal/profile'
    | '/_portal/recommendation'
    | '/_portal/referrals'
    | '/_portal/upload-documents'
    | '/_portal/verification'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PortalRoute: typeof PortalRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_portal': {
      id: '/_portal'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_portal/assessment': {
      id: '/_portal/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof PortalAssessmentRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/assistant': {
      id: '/_portal/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof PortalAssistantRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/cases': {
      id: '/_portal/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof PortalCasesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/dashboard': {
      id: '/_portal/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof PortalDashboardRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/debt-summary': {
      id: '/_portal/debt-summary'
      path: '/debt-summary'
      fullPath: '/debt-summary'
      preLoaderRoute: typeof PortalDebtSummaryRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/documents': {
      id: '/_portal/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof PortalDocumentsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/financial-summary': {
      id: '/_portal/financial-summary'
      path: '/financial-summary'
      fullPath: '/financial-summary'
      preLoaderRoute: typeof PortalFinancialSummaryRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/messages': {
      id: '/_portal/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof PortalMessagesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/profile': {
      id: '/_portal/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof PortalProfileRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/recommendation': {
      id: '/_portal/recommendation'
      path: '/recommendation'
      fullPath: '/recommendation'
      preLoaderRoute: typeof PortalRecommendationRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/referrals': {
      id: '/_portal/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof PortalReferralsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/upload-documents': {
      id: '/_portal/upload-documents'
      path: '/upload-documents'
      fullPath: '/upload-documents'
      preLoaderRoute: typeof PortalUploadDocumentsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/verification': {
      id: '/_portal/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof PortalVerificationRouteImport
      parentRoute: typeof PortalRoute
    }
  }
}

interface PortalRouteChildren {
  PortalAssessmentRoute: typeof PortalAssessmentRoute
  PortalAssistantRoute: typeof PortalAssistantRoute
  PortalCasesRoute: typeof PortalCasesRoute
  PortalDashboardRoute: typeof PortalDashboardRoute
  PortalDebtSummaryRoute: typeof PortalDebtSummaryRoute
  PortalDocumentsRoute: typeof PortalDocumentsRoute
  PortalFinancialSummaryRoute: typeof PortalFinancialSummaryRoute
  PortalMessagesRoute: typeof PortalMessagesRoute
  PortalProfileRoute: typeof PortalProfileRoute
  PortalRecommendationRoute: typeof PortalRecommendationRoute
  PortalReferralsRoute: typeof PortalReferralsRoute
  PortalUploadDocumentsRoute: typeof PortalUploadDocumentsRoute
  PortalVerificationRoute: typeof PortalVerificationRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalAssessmentRoute: PortalAssessmentRoute,
  PortalAssistantRoute: PortalAssistantRoute,
  PortalCasesRoute: PortalCasesRoute,
  PortalDashboardRoute: PortalDashboardRoute,
  PortalDebtSummaryRoute: PortalDebtSummaryRoute,
  PortalDocumentsRoute: PortalDocumentsRoute,
  PortalFinancialSummaryRoute: PortalFinancialSummaryRoute,
  PortalMessagesRoute: PortalMessagesRoute,
  PortalProfileRoute: PortalProfileRoute,
  PortalRecommendationRoute: PortalRecommendationRoute,
  PortalReferralsRoute: PortalReferralsRoute,
  PortalUploadDocumentsRoute: PortalUploadDocumentsRoute,
  PortalVerificationRoute: PortalVerificationRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PortalRoute: PortalRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
