/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalRouteImport } from './routes/_portal'
import { Route as SolicitorRouteImport } from './routes/_solicitor'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PortalAdviceRouteImport } from './routes/_portal.advice'
import { Route as PortalAffordabilityAssessmentRouteImport } from './routes/_portal.affordability-assessment'
import { Route as PortalAnswerQuestionsRouteImport } from './routes/_portal.answer-questions'
import { Route as PortalAssessmentRouteImport } from './routes/_portal.assessment'
import { Route as PortalAssistantRouteImport } from './routes/_portal.assistant'
import { Route as PortalCasesRouteImport } from './routes/_portal.cases'
import { Route as PortalDashboardRouteImport } from './routes/_portal.dashboard'
import { Route as PortalDebtCreditorInformationRouteImport } from './routes/_portal.debt-creditor-information'
import { Route as PortalDebtOptionsRouteImport } from './routes/_portal.debt-options'
import { Route as PortalDebtSummaryRouteImport } from './routes/_portal.debt-summary'
import { Route as PortalDocumentHelpRouteImport } from './routes/_portal.document-help'
import { Route as PortalDocumentsRouteImport } from './routes/_portal.documents'
import { Route as PortalExplainDebtOptionsRouteImport } from './routes/_portal.explain-debt-options'
import { Route as PortalFinancialInformationRouteImport } from './routes/_portal.financial-information'
import { Route as PortalFinancialSummaryRouteImport } from './routes/_portal.financial-summary'
import { Route as PortalMessagesRouteImport } from './routes/_portal.messages'
import { Route as PortalMissingEvidenceRouteImport } from './routes/_portal.missing-evidence'
import { Route as PortalProfileRouteImport } from './routes/_portal.profile'
import { Route as PortalRecommendationRouteImport } from './routes/_portal.recommendation'
import { Route as PortalReferralsRouteImport } from './routes/_portal.referrals'
import { Route as PortalRiskAssessmentRouteImport } from './routes/_portal.risk-assessment'
import { Route as PortalStatusUpdatesRouteImport } from './routes/_portal.status-updates'
import { Route as PortalUploadDocumentsRouteImport } from './routes/_portal.upload-documents'
import { Route as PortalVerificationRouteImport } from './routes/_portal.verification'
import { Route as PortalVulnerabilityAssessmentRouteImport } from './routes/_portal.vulnerability-assessment'
import { Route as SolicitorSolicitorIndexRouteImport } from './routes/_solicitor.solicitor.index'
import { Route as SolicitorSolicitorSplatRouteImport } from './routes/_solicitor.solicitor.$'
import { Route as SolicitorSolicitorAuditRouteImport } from './routes/_solicitor.solicitor.audit'
import { Route as SolicitorSolicitorDocumentsRouteImport } from './routes/_solicitor.solicitor.documents'
import { Route as SolicitorSolicitorNotificationsRouteImport } from './routes/_solicitor.solicitor.notifications'
import { Route as SolicitorSolicitorTasksRouteImport } from './routes/_solicitor.solicitor.tasks'
import { Route as SolicitorSolicitorMattersIndexRouteImport } from './routes/_solicitor.solicitor.matters.index'
import { Route as SolicitorSolicitorMattersMatterIdRouteImport } from './routes/_solicitor.solicitor.matters.$matterId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/_portal',
  getParentRoute: () => rootRouteImport,
} as any)
const SolicitorRoute = SolicitorRouteImport.update({
  id: '/_solicitor',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalAdviceRoute = PortalAdviceRouteImport.update({
  id: '/advice',
  path: '/advice',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAffordabilityAssessmentRoute =
  PortalAffordabilityAssessmentRouteImport.update({
    id: '/affordability-assessment',
    path: '/affordability-assessment',
    getParentRoute: () => PortalRoute,
  } as any)
const PortalAnswerQuestionsRoute = PortalAnswerQuestionsRouteImport.update({
  id: '/answer-questions',
  path: '/answer-questions',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAssessmentRoute = PortalAssessmentRouteImport.update({
  id: '/assessment',
  path: '/assessment',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAssistantRoute = PortalAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => PortalRoute,
} as any)
const PortalCasesRoute = PortalCasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDashboardRoute = PortalDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDebtCreditorInformationRoute =
  PortalDebtCreditorInformationRouteImport.update({
    id: '/debt-creditor-information',
    path: '/debt-creditor-information',
    getParentRoute: () => PortalRoute,
  } as any)
const PortalDebtOptionsRoute = PortalDebtOptionsRouteImport.update({
  id: '/debt-options',
  path: '/debt-options',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDebtSummaryRoute = PortalDebtSummaryRouteImport.update({
  id: '/debt-summary',
  path: '/debt-summary',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDocumentHelpRoute = PortalDocumentHelpRouteImport.update({
  id: '/document-help',
  path: '/document-help',
  getParentRoute: () => PortalRoute,
} as any)
const PortalDocumentsRoute = PortalDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => PortalRoute,
} as any)
const PortalExplainDebtOptionsRoute =
  PortalExplainDebtOptionsRouteImport.update({
    id: '/explain-debt-options',
    path: '/explain-debt-options',
    getParentRoute: () => PortalRoute,
  } as any)
const PortalFinancialInformationRoute =
  PortalFinancialInformationRouteImport.update({
    id: '/financial-information',
    path: '/financial-information',
    getParentRoute: () => PortalRoute,
  } as any)
const PortalFinancialSummaryRoute = PortalFinancialSummaryRouteImport.update({
  id: '/financial-summary',
  path: '/financial-summary',
  getParentRoute: () => PortalRoute,
} as any)
const PortalMessagesRoute = PortalMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => PortalRoute,
} as any)
const PortalMissingEvidenceRoute = PortalMissingEvidenceRouteImport.update({
  id: '/missing-evidence',
  path: '/missing-evidence',
  getParentRoute: () => PortalRoute,
} as any)
const PortalProfileRoute = PortalProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PortalRoute,
} as any)
const PortalRecommendationRoute = PortalRecommendationRouteImport.update({
  id: '/recommendation',
  path: '/recommendation',
  getParentRoute: () => PortalRoute,
} as any)
const PortalReferralsRoute = PortalReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => PortalRoute,
} as any)
const PortalRiskAssessmentRoute = PortalRiskAssessmentRouteImport.update({
  id: '/risk-assessment',
  path: '/risk-assessment',
  getParentRoute: () => PortalRoute,
} as any)
const PortalStatusUpdatesRoute = PortalStatusUpdatesRouteImport.update({
  id: '/status-updates',
  path: '/status-updates',
  getParentRoute: () => PortalRoute,
} as any)
const PortalUploadDocumentsRoute = PortalUploadDocumentsRouteImport.update({
  id: '/upload-documents',
  path: '/upload-documents',
  getParentRoute: () => PortalRoute,
} as any)
const PortalVerificationRoute = PortalVerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => PortalRoute,
} as any)
const PortalVulnerabilityAssessmentRoute =
  PortalVulnerabilityAssessmentRouteImport.update({
    id: '/vulnerability-assessment',
    path: '/vulnerability-assessment',
    getParentRoute: () => PortalRoute,
  } as any)
const SolicitorSolicitorIndexRoute = SolicitorSolicitorIndexRouteImport.update({
  id: '/solicitor/',
  path: '/solicitor/',
  getParentRoute: () => SolicitorRoute,
} as any)
const SolicitorSolicitorSplatRoute = SolicitorSolicitorSplatRouteImport.update({
  id: '/solicitor/$',
  path: '/solicitor/$',
  getParentRoute: () => SolicitorRoute,
} as any)
const SolicitorSolicitorAuditRoute = SolicitorSolicitorAuditRouteImport.update({
  id: '/solicitor/audit',
  path: '/solicitor/audit',
  getParentRoute: () => SolicitorRoute,
} as any)
const SolicitorSolicitorDocumentsRoute =
  SolicitorSolicitorDocumentsRouteImport.update({
    id: '/solicitor/documents',
    path: '/solicitor/documents',
    getParentRoute: () => SolicitorRoute,
  } as any)
const SolicitorSolicitorNotificationsRoute =
  SolicitorSolicitorNotificationsRouteImport.update({
    id: '/solicitor/notifications',
    path: '/solicitor/notifications',
    getParentRoute: () => SolicitorRoute,
  } as any)
const SolicitorSolicitorTasksRoute = SolicitorSolicitorTasksRouteImport.update({
  id: '/solicitor/tasks',
  path: '/solicitor/tasks',
  getParentRoute: () => SolicitorRoute,
} as any)
const SolicitorSolicitorMattersIndexRoute =
  SolicitorSolicitorMattersIndexRouteImport.update({
    id: '/solicitor/matters/',
    path: '/solicitor/matters/',
    getParentRoute: () => SolicitorRoute,
  } as any)
const SolicitorSolicitorMattersMatterIdRoute =
  SolicitorSolicitorMattersMatterIdRouteImport.update({
    id: '/solicitor/matters/$matterId',
    path: '/solicitor/matters/$matterId',
    getParentRoute: () => SolicitorRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/advice': typeof PortalAdviceRoute
  '/affordability-assessment': typeof PortalAffordabilityAssessmentRoute
  '/answer-questions': typeof PortalAnswerQuestionsRoute
  '/assessment': typeof PortalAssessmentRoute
  '/assistant': typeof PortalAssistantRoute
  '/cases': typeof PortalCasesRoute
  '/dashboard': typeof PortalDashboardRoute
  '/debt-creditor-information': typeof PortalDebtCreditorInformationRoute
  '/debt-options': typeof PortalDebtOptionsRoute
  '/debt-summary': typeof PortalDebtSummaryRoute
  '/document-help': typeof PortalDocumentHelpRoute
  '/documents': typeof PortalDocumentsRoute
  '/explain-debt-options': typeof PortalExplainDebtOptionsRoute
  '/financial-information': typeof PortalFinancialInformationRoute
  '/financial-summary': typeof PortalFinancialSummaryRoute
  '/messages': typeof PortalMessagesRoute
  '/missing-evidence': typeof PortalMissingEvidenceRoute
  '/profile': typeof PortalProfileRoute
  '/recommendation': typeof PortalRecommendationRoute
  '/referrals': typeof PortalReferralsRoute
  '/risk-assessment': typeof PortalRiskAssessmentRoute
  '/status-updates': typeof PortalStatusUpdatesRoute
  '/upload-documents': typeof PortalUploadDocumentsRoute
  '/verification': typeof PortalVerificationRoute
  '/vulnerability-assessment': typeof PortalVulnerabilityAssessmentRoute
  '/solicitor/$': typeof SolicitorSolicitorSplatRoute
  '/solicitor/audit': typeof SolicitorSolicitorAuditRoute
  '/solicitor/documents': typeof SolicitorSolicitorDocumentsRoute
  '/solicitor/notifications': typeof SolicitorSolicitorNotificationsRoute
  '/solicitor/tasks': typeof SolicitorSolicitorTasksRoute
  '/solicitor/': typeof SolicitorSolicitorIndexRoute
  '/solicitor/matters/$matterId': typeof SolicitorSolicitorMattersMatterIdRoute
  '/solicitor/matters/': typeof SolicitorSolicitorMattersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/advice': typeof PortalAdviceRoute
  '/affordability-assessment': typeof PortalAffordabilityAssessmentRoute
  '/answer-questions': typeof PortalAnswerQuestionsRoute
  '/assessment': typeof PortalAssessmentRoute
  '/assistant': typeof PortalAssistantRoute
  '/cases': typeof PortalCasesRoute
  '/dashboard': typeof PortalDashboardRoute
  '/debt-creditor-information': typeof PortalDebtCreditorInformationRoute
  '/debt-options': typeof PortalDebtOptionsRoute
  '/debt-summary': typeof PortalDebtSummaryRoute
  '/document-help': typeof PortalDocumentHelpRoute
  '/documents': typeof PortalDocumentsRoute
  '/explain-debt-options': typeof PortalExplainDebtOptionsRoute
  '/financial-information': typeof PortalFinancialInformationRoute
  '/financial-summary': typeof PortalFinancialSummaryRoute
  '/messages': typeof PortalMessagesRoute
  '/missing-evidence': typeof PortalMissingEvidenceRoute
  '/profile': typeof PortalProfileRoute
  '/recommendation': typeof PortalRecommendationRoute
  '/referrals': typeof PortalReferralsRoute
  '/risk-assessment': typeof PortalRiskAssessmentRoute
  '/status-updates': typeof PortalStatusUpdatesRoute
  '/upload-documents': typeof PortalUploadDocumentsRoute
  '/verification': typeof PortalVerificationRoute
  '/vulnerability-assessment': typeof PortalVulnerabilityAssessmentRoute
  '/solicitor/$': typeof SolicitorSolicitorSplatRoute
  '/solicitor/audit': typeof SolicitorSolicitorAuditRoute
  '/solicitor/documents': typeof SolicitorSolicitorDocumentsRoute
  '/solicitor/notifications': typeof SolicitorSolicitorNotificationsRoute
  '/solicitor/tasks': typeof SolicitorSolicitorTasksRoute
  '/solicitor': typeof SolicitorSolicitorIndexRoute
  '/solicitor/matters/$matterId': typeof SolicitorSolicitorMattersMatterIdRoute
  '/solicitor/matters': typeof SolicitorSolicitorMattersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_portal': typeof PortalRouteWithChildren
  '/_solicitor': typeof SolicitorRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_portal/advice': typeof PortalAdviceRoute
  '/_portal/affordability-assessment': typeof PortalAffordabilityAssessmentRoute
  '/_portal/answer-questions': typeof PortalAnswerQuestionsRoute
  '/_portal/assessment': typeof PortalAssessmentRoute
  '/_portal/assistant': typeof PortalAssistantRoute
  '/_portal/cases': typeof PortalCasesRoute
  '/_portal/dashboard': typeof PortalDashboardRoute
  '/_portal/debt-creditor-information': typeof PortalDebtCreditorInformationRoute
  '/_portal/debt-options': typeof PortalDebtOptionsRoute
  '/_portal/debt-summary': typeof PortalDebtSummaryRoute
  '/_portal/document-help': typeof PortalDocumentHelpRoute
  '/_portal/documents': typeof PortalDocumentsRoute
  '/_portal/explain-debt-options': typeof PortalExplainDebtOptionsRoute
  '/_portal/financial-information': typeof PortalFinancialInformationRoute
  '/_portal/financial-summary': typeof PortalFinancialSummaryRoute
  '/_portal/messages': typeof PortalMessagesRoute
  '/_portal/missing-evidence': typeof PortalMissingEvidenceRoute
  '/_portal/profile': typeof PortalProfileRoute
  '/_portal/recommendation': typeof PortalRecommendationRoute
  '/_portal/referrals': typeof PortalReferralsRoute
  '/_portal/risk-assessment': typeof PortalRiskAssessmentRoute
  '/_portal/status-updates': typeof PortalStatusUpdatesRoute
  '/_portal/upload-documents': typeof PortalUploadDocumentsRoute
  '/_portal/verification': typeof PortalVerificationRoute
  '/_portal/vulnerability-assessment': typeof PortalVulnerabilityAssessmentRoute
  '/_solicitor/solicitor/$': typeof SolicitorSolicitorSplatRoute
  '/_solicitor/solicitor/audit': typeof SolicitorSolicitorAuditRoute
  '/_solicitor/solicitor/documents': typeof SolicitorSolicitorDocumentsRoute
  '/_solicitor/solicitor/notifications': typeof SolicitorSolicitorNotificationsRoute
  '/_solicitor/solicitor/tasks': typeof SolicitorSolicitorTasksRoute
  '/_solicitor/solicitor/': typeof SolicitorSolicitorIndexRoute
  '/_solicitor/solicitor/matters/$matterId': typeof SolicitorSolicitorMattersMatterIdRoute
  '/_solicitor/solicitor/matters/': typeof SolicitorSolicitorMattersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/advice'
    | '/affordability-assessment'
    | '/answer-questions'
    | '/assessment'
    | '/assistant'
    | '/cases'
    | '/dashboard'
    | '/debt-creditor-information'
    | '/debt-options'
    | '/debt-summary'
    | '/document-help'
    | '/documents'
    | '/explain-debt-options'
    | '/financial-information'
    | '/financial-summary'
    | '/messages'
    | '/missing-evidence'
    | '/profile'
    | '/recommendation'
    | '/referrals'
    | '/risk-assessment'
    | '/status-updates'
    | '/upload-documents'
    | '/verification'
    | '/vulnerability-assessment'
    | '/solicitor/$'
    | '/solicitor/audit'
    | '/solicitor/documents'
    | '/solicitor/notifications'
    | '/solicitor/tasks'
    | '/solicitor/'
    | '/solicitor/matters/$matterId'
    | '/solicitor/matters/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/advice'
    | '/affordability-assessment'
    | '/answer-questions'
    | '/assessment'
    | '/assistant'
    | '/cases'
    | '/dashboard'
    | '/debt-creditor-information'
    | '/debt-options'
    | '/debt-summary'
    | '/document-help'
    | '/documents'
    | '/explain-debt-options'
    | '/financial-information'
    | '/financial-summary'
    | '/messages'
    | '/missing-evidence'
    | '/profile'
    | '/recommendation'
    | '/referrals'
    | '/risk-assessment'
    | '/status-updates'
    | '/upload-documents'
    | '/verification'
    | '/vulnerability-assessment'
    | '/solicitor/$'
    | '/solicitor/audit'
    | '/solicitor/documents'
    | '/solicitor/notifications'
    | '/solicitor/tasks'
    | '/solicitor'
    | '/solicitor/matters/$matterId'
    | '/solicitor/matters'
  id:
    | '__root__'
    | '/'
    | '/_portal'
    | '/_solicitor'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/_portal/advice'
    | '/_portal/affordability-assessment'
    | '/_portal/answer-questions'
    | '/_portal/assessment'
    | '/_portal/assistant'
    | '/_portal/cases'
    | '/_portal/dashboard'
    | '/_portal/debt-creditor-information'
    | '/_portal/debt-options'
    | '/_portal/debt-summary'
    | '/_portal/document-help'
    | '/_portal/documents'
    | '/_portal/explain-debt-options'
    | '/_portal/financial-information'
    | '/_portal/financial-summary'
    | '/_portal/messages'
    | '/_portal/missing-evidence'
    | '/_portal/profile'
    | '/_portal/recommendation'
    | '/_portal/referrals'
    | '/_portal/risk-assessment'
    | '/_portal/status-updates'
    | '/_portal/upload-documents'
    | '/_portal/verification'
    | '/_portal/vulnerability-assessment'
    | '/_solicitor/solicitor/$'
    | '/_solicitor/solicitor/audit'
    | '/_solicitor/solicitor/documents'
    | '/_solicitor/solicitor/notifications'
    | '/_solicitor/solicitor/tasks'
    | '/_solicitor/solicitor/'
    | '/_solicitor/solicitor/matters/$matterId'
    | '/_solicitor/solicitor/matters/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PortalRoute: typeof PortalRouteWithChildren
  SolicitorRoute: typeof SolicitorRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_portal': {
      id: '/_portal'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_solicitor': {
      id: '/_solicitor'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SolicitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_portal/advice': {
      id: '/_portal/advice'
      path: '/advice'
      fullPath: '/advice'
      preLoaderRoute: typeof PortalAdviceRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/affordability-assessment': {
      id: '/_portal/affordability-assessment'
      path: '/affordability-assessment'
      fullPath: '/affordability-assessment'
      preLoaderRoute: typeof PortalAffordabilityAssessmentRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/answer-questions': {
      id: '/_portal/answer-questions'
      path: '/answer-questions'
      fullPath: '/answer-questions'
      preLoaderRoute: typeof PortalAnswerQuestionsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/assessment': {
      id: '/_portal/assessment'
      path: '/assessment'
      fullPath: '/assessment'
      preLoaderRoute: typeof PortalAssessmentRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/assistant': {
      id: '/_portal/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof PortalAssistantRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/cases': {
      id: '/_portal/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof PortalCasesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/dashboard': {
      id: '/_portal/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof PortalDashboardRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/debt-creditor-information': {
      id: '/_portal/debt-creditor-information'
      path: '/debt-creditor-information'
      fullPath: '/debt-creditor-information'
      preLoaderRoute: typeof PortalDebtCreditorInformationRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/debt-options': {
      id: '/_portal/debt-options'
      path: '/debt-options'
      fullPath: '/debt-options'
      preLoaderRoute: typeof PortalDebtOptionsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/debt-summary': {
      id: '/_portal/debt-summary'
      path: '/debt-summary'
      fullPath: '/debt-summary'
      preLoaderRoute: typeof PortalDebtSummaryRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/document-help': {
      id: '/_portal/document-help'
      path: '/document-help'
      fullPath: '/document-help'
      preLoaderRoute: typeof PortalDocumentHelpRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/documents': {
      id: '/_portal/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof PortalDocumentsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/explain-debt-options': {
      id: '/_portal/explain-debt-options'
      path: '/explain-debt-options'
      fullPath: '/explain-debt-options'
      preLoaderRoute: typeof PortalExplainDebtOptionsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/financial-information': {
      id: '/_portal/financial-information'
      path: '/financial-information'
      fullPath: '/financial-information'
      preLoaderRoute: typeof PortalFinancialInformationRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/financial-summary': {
      id: '/_portal/financial-summary'
      path: '/financial-summary'
      fullPath: '/financial-summary'
      preLoaderRoute: typeof PortalFinancialSummaryRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/messages': {
      id: '/_portal/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof PortalMessagesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/missing-evidence': {
      id: '/_portal/missing-evidence'
      path: '/missing-evidence'
      fullPath: '/missing-evidence'
      preLoaderRoute: typeof PortalMissingEvidenceRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/profile': {
      id: '/_portal/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof PortalProfileRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/recommendation': {
      id: '/_portal/recommendation'
      path: '/recommendation'
      fullPath: '/recommendation'
      preLoaderRoute: typeof PortalRecommendationRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/referrals': {
      id: '/_portal/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof PortalReferralsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/risk-assessment': {
      id: '/_portal/risk-assessment'
      path: '/risk-assessment'
      fullPath: '/risk-assessment'
      preLoaderRoute: typeof PortalRiskAssessmentRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/status-updates': {
      id: '/_portal/status-updates'
      path: '/status-updates'
      fullPath: '/status-updates'
      preLoaderRoute: typeof PortalStatusUpdatesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/upload-documents': {
      id: '/_portal/upload-documents'
      path: '/upload-documents'
      fullPath: '/upload-documents'
      preLoaderRoute: typeof PortalUploadDocumentsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/verification': {
      id: '/_portal/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof PortalVerificationRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/vulnerability-assessment': {
      id: '/_portal/vulnerability-assessment'
      path: '/vulnerability-assessment'
      fullPath: '/vulnerability-assessment'
      preLoaderRoute: typeof PortalVulnerabilityAssessmentRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_solicitor/solicitor/': {
      id: '/_solicitor/solicitor/'
      path: '/solicitor'
      fullPath: '/solicitor/'
      preLoaderRoute: typeof SolicitorSolicitorIndexRouteImport
      parentRoute: typeof SolicitorRoute
    }
    '/_solicitor/solicitor/$': {
      id: '/_solicitor/solicitor/$'
      path: '/solicitor/$'
      fullPath: '/solicitor/$'
      preLoaderRoute: typeof SolicitorSolicitorSplatRouteImport
      parentRoute: typeof SolicitorRoute
    }
    '/_solicitor/solicitor/audit': {
      id: '/_solicitor/solicitor/audit'
      path: '/solicitor/audit'
      fullPath: '/solicitor/audit'
      preLoaderRoute: typeof SolicitorSolicitorAuditRouteImport
      parentRoute: typeof SolicitorRoute
    }
    '/_solicitor/solicitor/documents': {
      id: '/_solicitor/solicitor/documents'
      path: '/solicitor/documents'
      fullPath: '/solicitor/documents'
      preLoaderRoute: typeof SolicitorSolicitorDocumentsRouteImport
      parentRoute: typeof SolicitorRoute
    }
    '/_solicitor/solicitor/notifications': {
      id: '/_solicitor/solicitor/notifications'
      path: '/solicitor/notifications'
      fullPath: '/solicitor/notifications'
      preLoaderRoute: typeof SolicitorSolicitorNotificationsRouteImport
      parentRoute: typeof SolicitorRoute
    }
    '/_solicitor/solicitor/tasks': {
      id: '/_solicitor/solicitor/tasks'
      path: '/solicitor/tasks'
      fullPath: '/solicitor/tasks'
      preLoaderRoute: typeof SolicitorSolicitorTasksRouteImport
      parentRoute: typeof SolicitorRoute
    }
    '/_solicitor/solicitor/matters/': {
      id: '/_solicitor/solicitor/matters/'
      path: '/solicitor/matters'
      fullPath: '/solicitor/matters/'
      preLoaderRoute: typeof SolicitorSolicitorMattersIndexRouteImport
      parentRoute: typeof SolicitorRoute
    }
    '/_solicitor/solicitor/matters/$matterId': {
      id: '/_solicitor/solicitor/matters/$matterId'
      path: '/solicitor/matters/$matterId'
      fullPath: '/solicitor/matters/$matterId'
      preLoaderRoute: typeof SolicitorSolicitorMattersMatterIdRouteImport
      parentRoute: typeof SolicitorRoute
    }
  }
}

interface PortalRouteChildren {
  PortalAdviceRoute: typeof PortalAdviceRoute
  PortalAffordabilityAssessmentRoute: typeof PortalAffordabilityAssessmentRoute
  PortalAnswerQuestionsRoute: typeof PortalAnswerQuestionsRoute
  PortalAssessmentRoute: typeof PortalAssessmentRoute
  PortalAssistantRoute: typeof PortalAssistantRoute
  PortalCasesRoute: typeof PortalCasesRoute
  PortalDashboardRoute: typeof PortalDashboardRoute
  PortalDebtCreditorInformationRoute: typeof PortalDebtCreditorInformationRoute
  PortalDebtOptionsRoute: typeof PortalDebtOptionsRoute
  PortalDebtSummaryRoute: typeof PortalDebtSummaryRoute
  PortalDocumentHelpRoute: typeof PortalDocumentHelpRoute
  PortalDocumentsRoute: typeof PortalDocumentsRoute
  PortalExplainDebtOptionsRoute: typeof PortalExplainDebtOptionsRoute
  PortalFinancialInformationRoute: typeof PortalFinancialInformationRoute
  PortalFinancialSummaryRoute: typeof PortalFinancialSummaryRoute
  PortalMessagesRoute: typeof PortalMessagesRoute
  PortalMissingEvidenceRoute: typeof PortalMissingEvidenceRoute
  PortalProfileRoute: typeof PortalProfileRoute
  PortalRecommendationRoute: typeof PortalRecommendationRoute
  PortalReferralsRoute: typeof PortalReferralsRoute
  PortalRiskAssessmentRoute: typeof PortalRiskAssessmentRoute
  PortalStatusUpdatesRoute: typeof PortalStatusUpdatesRoute
  PortalUploadDocumentsRoute: typeof PortalUploadDocumentsRoute
  PortalVerificationRoute: typeof PortalVerificationRoute
  PortalVulnerabilityAssessmentRoute: typeof PortalVulnerabilityAssessmentRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalAdviceRoute: PortalAdviceRoute,
  PortalAffordabilityAssessmentRoute: PortalAffordabilityAssessmentRoute,
  PortalAnswerQuestionsRoute: PortalAnswerQuestionsRoute,
  PortalAssessmentRoute: PortalAssessmentRoute,
  PortalAssistantRoute: PortalAssistantRoute,
  PortalCasesRoute: PortalCasesRoute,
  PortalDashboardRoute: PortalDashboardRoute,
  PortalDebtCreditorInformationRoute: PortalDebtCreditorInformationRoute,
  PortalDebtOptionsRoute: PortalDebtOptionsRoute,
  PortalDebtSummaryRoute: PortalDebtSummaryRoute,
  PortalDocumentHelpRoute: PortalDocumentHelpRoute,
  PortalDocumentsRoute: PortalDocumentsRoute,
  PortalExplainDebtOptionsRoute: PortalExplainDebtOptionsRoute,
  PortalFinancialInformationRoute: PortalFinancialInformationRoute,
  PortalFinancialSummaryRoute: PortalFinancialSummaryRoute,
  PortalMessagesRoute: PortalMessagesRoute,
  PortalMissingEvidenceRoute: PortalMissingEvidenceRoute,
  PortalProfileRoute: PortalProfileRoute,
  PortalRecommendationRoute: PortalRecommendationRoute,
  PortalReferralsRoute: PortalReferralsRoute,
  PortalRiskAssessmentRoute: PortalRiskAssessmentRoute,
  PortalStatusUpdatesRoute: PortalStatusUpdatesRoute,
  PortalUploadDocumentsRoute: PortalUploadDocumentsRoute,
  PortalVerificationRoute: PortalVerificationRoute,
  PortalVulnerabilityAssessmentRoute: PortalVulnerabilityAssessmentRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

interface SolicitorRouteChildren {
  SolicitorSolicitorSplatRoute: typeof SolicitorSolicitorSplatRoute
  SolicitorSolicitorAuditRoute: typeof SolicitorSolicitorAuditRoute
  SolicitorSolicitorDocumentsRoute: typeof SolicitorSolicitorDocumentsRoute
  SolicitorSolicitorNotificationsRoute: typeof SolicitorSolicitorNotificationsRoute
  SolicitorSolicitorTasksRoute: typeof SolicitorSolicitorTasksRoute
  SolicitorSolicitorIndexRoute: typeof SolicitorSolicitorIndexRoute
  SolicitorSolicitorMattersMatterIdRoute: typeof SolicitorSolicitorMattersMatterIdRoute
  SolicitorSolicitorMattersIndexRoute: typeof SolicitorSolicitorMattersIndexRoute
}

const SolicitorRouteChildren: SolicitorRouteChildren = {
  SolicitorSolicitorSplatRoute: SolicitorSolicitorSplatRoute,
  SolicitorSolicitorAuditRoute: SolicitorSolicitorAuditRoute,
  SolicitorSolicitorDocumentsRoute: SolicitorSolicitorDocumentsRoute,
  SolicitorSolicitorNotificationsRoute: SolicitorSolicitorNotificationsRoute,
  SolicitorSolicitorTasksRoute: SolicitorSolicitorTasksRoute,
  SolicitorSolicitorIndexRoute: SolicitorSolicitorIndexRoute,
  SolicitorSolicitorMattersMatterIdRoute:
    SolicitorSolicitorMattersMatterIdRoute,
  SolicitorSolicitorMattersIndexRoute: SolicitorSolicitorMattersIndexRoute,
}

const SolicitorRouteWithChildren = SolicitorRoute._addFileChildren(
  SolicitorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PortalRoute: PortalRouteWithChildren,
  SolicitorRoute: SolicitorRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
